// Import videos explicitly to avoid caching issues
const lx4toursVideo = require('@/assets/videos/lx4tours.mp4');
const puppybondVideo = require('@/assets/videos/puppybond_1.mp4');
const escala25Video = require('@/assets/videos/escala25.mp4');

export interface Experience {
  id: string;
  title: string;
  provider: string;
  providerLogo?: any;
  location: string;
  distance: string;
  price: number;
  currency: string;
  duration: string;
  rating: number;
  reviewCount: number;
  image: string;
  video?: any;
  images?: any[];
  category: string;
  tags: string[];
  description: string;
  highlights: string[];
  included: string[];
  meetingPoint: string;
  latitude: number;
  longitude: number;
  availableToday: boolean;
  instantBooking: boolean;
  verified: boolean;
  maxGroupSize?: number;
  languages?: string[];
  whatToBring?: string[];
  cancellationPolicy?: string;
  importantInfo?: string;
}

export const EXPERIENCES: Experience[] = [
  {
    id: '0',
    title: 'Atlantic Coast Guided Quad Bike Tour',
    provider: 'LX4Tours',
    providerLogo: require('@/assets/images/lxtourslogo.png'),
    location: 'Costa da Caparica',
    distance: '15km away',
    price: 99,
    currency: '€',
    duration: '2h',
    rating: 4.9,
    reviewCount: 835,
    image: 'https://images.unsplash.com/photo-1558618666-fcd25c85cd64?w=800&q=80',
    video: lx4toursVideo,
    images: [
      require('@/assets/images/lxtours1.png'),
      require('@/assets/images/lxtours2.png'),
      require('@/assets/images/lxtours3.png'),
      require('@/assets/images/lxtours4.png'),
    ],
    category: 'Adventure',
    tags: ['Quad Bikes', 'Beach', 'Off-Road', 'Nature', 'Outdoor'],
    description: 'Explore the wild side of Lisbon on a relaxed and guided quad bike tour. Embark on an immersive adventure and discover secret places, unknown stories and local culture. Navigate quiet roads to build confidence on your quad bike. Feel the wind in your face as you head to an abandoned WWI military complex built to protect the gates of Europe.',
    highlights: [
      'Explore the wild side of Lisbon',
      'Learn about Portuguese history, myths and legends',
      'Unlock exclusive access to hidden places, inaccessible any other way',
      'Take amazing photos and videos with incredible views',
      'Discover the local community and learn about their culture',
      'Visit the Portuguese Grand Canyon - as old as time itself',
      'See an abandoned 1980s water park hidden on top of the canyon',
      'Discover a 16th century monastery built by a mysterious Portuguese family',
      'Face challenging trails while driving through the forest',
    ],
    included: [
      'Quad bike tour',
      'Professional guide',
      'Safety instructions',
      'Protective equipment (helmet & gear)',
      'Health insurance',
    ],
    meetingPoint: 'R. Frei Bartolomeu Assunção 15, Costa de Caparica - Look for the Portuguese flag on a white wall, red barrels and blue containers',
    latitude: 38.63798904418945,
    longitude: -9.231167793273926,
    availableToday: true,
    instantBooking: true,
    verified: true,
    maxGroupSize: 8,
    languages: ['Portuguese', 'English', 'French'],
    whatToBring: ['Driver\'s license'],
    cancellationPolicy: 'Free cancellation up to 24 hours in advance for a full refund',
    importantInfo: 'Drivers can switch multiple times during the tour. The passenger experience is also an adventure in itself. This description refers to the most common route used on this tour. The itinerary may differ from tour to tour depending on various factors.',
  },
  {
    id: '1',
    title: 'Puppy Yoga - Relaxa e Conecta-te com Cachorros',
    provider: 'Puppy Bond',
    providerLogo: require('@/assets/images/pupyylogo.webp'),
    location: 'Lisboa',
    distance: '3km away',
    price: 25,
    currency: '€',
    duration: '1h15',
    rating: 4.8,
    reviewCount: 342,
    image: 'https://images.unsplash.com/photo-1544551763-46a013bb70d5?w=800&q=80',
    video: puppybondVideo,
    images: [
      require('@/assets/images/puppy1.webp'),
      require('@/assets/images/puppy2.webp'),
      require('@/assets/images/puppy3.webp'),
      require('@/assets/images/puppy4.webp'),
    ],
    category: 'Workshop',
    tags: ['Yoga', 'Animals', 'Wellness', 'Relax', 'Unique'],
    description: 'O Puppy Yoga junta o melhor de dois mundos: os benefícios do yoga e a alegria contagiante dos cachorros. É uma experiência diferente, perfeita para relaxares, melhorares o teu bem-estar e viveres momentos cheios de carinho.',
    highlights: [
      'Reduzir o stress e a ansiedade através de técnicas de respiração e relaxamento',
      'Aumentar a felicidade — a interação com os cachorros liberta serotonina e endorfinas',
      'Fortalecer o corpo e ganhar flexibilidade, mesmo que estejas a começar no yoga',
      'Melhorar a concentração e a postura, levando mais equilíbrio para o teu dia a dia',
      'Sentir o conforto emocional do contacto com animais, uma verdadeira terapia de bem-estar',
      'Descobrir uma atividade diferente, ideal para fazer sozinho ou com amigos',
      'Contribuir para a adoção responsável de cães',
    ],
    included: [
      '15 minutos iniciais para interagir com os cachorrinhos',
      '45 minutos de yoga guiado',
      '15 minutos finais para fotos e mais interação',
      'Todos os materiais de yoga',
      'Seguro',
    ],
    meetingPoint: 'Vários locais em Lisboa - confirmado após reserva',
    latitude: 38.7223,
    longitude: -9.1393,
    availableToday: true,
    instantBooking: true,
    verified: true,
    maxGroupSize: 20,
    languages: ['Português', 'English'],
    whatToBring: ['Roupa confortável para yoga', 'Água', 'Tapete de yoga (opcional)'],
    cancellationPolicy: 'Cancelamento gratuito até 24 horas antes da sessão para reembolso total',
    importantInfo: 'Parte do valor de cada bilhete é doado às associações de proteção animal. Alguns cães podem estar disponíveis para adoção responsável.',
  },
  {
    id: '2',
    title: 'Experiência de Escalada Guiada na Ponte 25 de Abril',
    provider: 'Escala25',
    providerLogo: require('@/assets/images/escala25logo.jpeg'),
    location: 'Lisboa - Ponte 25 de Abril',
    distance: '5km away',
    price: 30,
    currency: '€',
    duration: '1h',
    rating: 4.8,
    reviewCount: 14,
    image: 'https://images.unsplash.com/photo-1522163182402-834f871fd851?w=800&q=80',
    video: escala25Video,
    images: [
      require('@/assets/images/escala251.jpg'),
      require('@/assets/images/escala252.jpg'),
      require('@/assets/images/escala253.jpg'),
      require('@/assets/images/escala254.jpg'),
    ],
    category: 'Adventure',
    tags: ['Climbing', 'Outdoor', 'Sports', 'Adrenaline', 'Bridge'],
    description: 'Visite uma das principais aventuras ao ar livre de Lisboa e suba a uma das estruturas mais emblemáticas da cidade, a Ponte 25 de Abril. Aprenda o básico de escalada, boulder e auto-segurança, ou participe do curso de nível médio e melhore seu conhecimento sobre o trabalho com nós.',
    highlights: [
      'Sinta a adrenalina de subir a imponente Ponte 25 de Abril em Lisboa',
      'Aprenda o básico da escalada e se familiarize com o boulder e a auto-segurança',
      'Passe o dia explorando as instalações de escalada da Ponte 25 de Abril por conta própria',
      'Escolha entre uma aula para iniciantes em escalada ou um curso de introdução de nível médio',
      'Conheça os meandros dos fundamentos da escalada, como o trabalho com nós e cordas',
      'Várias rotas de escalada de até 40 pés (12 metros) de altura',
    ],
    included: [
      '1 hora de curso de escalada',
      'Equipamento de segurança',
      'Acesso a áreas de boulder e auto-belay',
      'Instrutor profissional',
    ],
    meetingPoint: 'Pilar 7 Experience - Av. da Índia, Lisboa. Do estacionamento, dirija-se à recepção para retirar seu ingresso.',
    latitude: 38.70038604736328,
    longitude: -9.178533554077148,
    availableToday: true,
    instantBooking: true,
    verified: true,
    maxGroupSize: 10,
    languages: ['Português', 'English'],
    whatToBring: ['Protetor solar', 'Água', 'Roupa confortável'],
    cancellationPolicy: 'Cancelamento gratuito até 24 horas de antecedência e obtenha reembolso integral',
    importantInfo: 'Esta atividade envolve escalar a alturas de até 40 pés (12 metros). Não indicado para crianças menores de 6 anos, pessoas com mobilidade reduzida ou maiores de 95 anos.',
  },
  {
    id: '3',
    title: 'Secret Food Tour: Alfama',
    provider: 'Taste of Lisboa',
    location: 'Lisbon',
    distance: '0.8km away',
    price: 75,
    currency: '€',
    duration: '3.5h',
    rating: 5.0,
    reviewCount: 341,
    image: 'https://images.unsplash.com/photo-1555939594-58d7cb561ad1?w=800&q=80',
    category: 'Food & Drink',
    tags: ['Food', 'Culture', 'Local'],
    description: 'Discover the hidden culinary gems of Alfama. Taste authentic Portuguese dishes while exploring narrow cobblestone streets and local secrets.',
    highlights: [
      'Visit 6 authentic local spots',
      'Try traditional Portuguese dishes',
      'Learn about local culture & history',
      'Small groups (max 10 people)'
    ],
    included: ['Food & drinks', 'Expert local guide', 'Secret locations'],
    meetingPoint: 'Miradouro de Santa Luzia',
    latitude: 38.7115,
    longitude: -9.1281,
    availableToday: false,
    instantBooking: true,
    verified: true,
  },
  {
    id: '4',
    title: 'Surf Lesson at Costa da Caparica',
    provider: 'Atlantic Surf School',
    location: 'Costa da Caparica',
    distance: '15km away',
    price: 35,
    currency: '€',
    duration: '2h',
    rating: 4.7,
    reviewCount: 189,
    image: 'https://images.unsplash.com/photo-1502933691298-84fc14542831?w=800&q=80',
    category: 'Adventure',
    tags: ['Surf', 'Beach', 'Active'],
    description: 'Learn to surf on one of Portugal\'s best beaches. Professional instructors will have you riding waves in no time!',
    highlights: [
      'Perfect for beginners',
      'All equipment provided',
      'Certified instructors',
      'Beautiful Atlantic beach'
    ],
    included: ['Surfboard', 'Wetsuit', 'Insurance', 'Photos'],
    meetingPoint: 'Praia do Surf, Costa da Caparica',
    latitude: 38.6333,
    longitude: -9.2333,
    availableToday: true,
    instantBooking: true,
    verified: true,
  },
  {
    id: '5',
    title: 'Fado Night Experience',
    provider: 'Casa do Fado',
    location: 'Bairro Alto',
    distance: '1.5km away',
    price: 55,
    currency: '€',
    duration: '2.5h',
    rating: 4.9,
    reviewCount: 278,
    image: 'https://images.unsplash.com/photo-1514525253161-7a46d19cd819?w=800&q=80',
    category: 'Music & Culture',
    tags: ['Music', 'Culture', 'Evening'],
    description: 'Experience authentic Fado music in an intimate traditional venue. Includes dinner and Portuguese wine.',
    highlights: [
      'Live Fado performance',
      'Traditional Portuguese dinner',
      'Historic venue',
      'Wine included'
    ],
    included: ['3-course dinner', 'Wine', 'Live music', 'Reserved seating'],
    meetingPoint: 'Rua da Rosa 123, Bairro Alto',
    latitude: 38.7142,
    longitude: -9.1459,
    availableToday: true,
    instantBooking: false,
    verified: true,
  },
  {
    id: '6',
    title: 'Street Art Walking Tour',
    provider: 'Urban Art Lisboa',
    location: 'LX Factory',
    distance: '3km away',
    price: 25,
    currency: '€',
    duration: '2h',
    rating: 4.6,
    reviewCount: 156,
    image: 'https://images.unsplash.com/photo-1499781350541-7783f6c6a0c8?w=800&q=80',
    category: 'Art & Culture',
    tags: ['Art', 'Urban', 'Photography'],
    description: 'Explore Lisbon\'s vibrant street art scene. Discover hidden murals and learn about the artists behind them.',
    highlights: [
      'Visit famous street art spots',
      'Learn about local artists',
      'Great for photography',
      'Off-the-beaten-path locations'
    ],
    included: ['Expert guide', 'Map of art locations', 'Coffee break'],
    meetingPoint: 'LX Factory Main Entrance',
    latitude: 38.7029,
    longitude: -9.1794,
    availableToday: true,
    instantBooking: true,
    verified: true,
  },
  {
    id: '7',
    title: 'E-Bike Tour: 7 Hills of Lisbon',
    provider: 'Lisbon Bike Tours',
    location: 'Baixa',
    distance: '0.5km away',
    price: 50,
    currency: '€',
    duration: '3h',
    rating: 4.8,
    reviewCount: 224,
    image: 'https://images.unsplash.com/photo-1571068316344-75bc76f77890?w=800&q=80',
    category: 'Tours',
    tags: ['Active', 'Sightseeing', 'E-bike'],
    description: 'Conquer Lisbon\'s famous seven hills effortlessly on an electric bike. See all major landmarks in one tour.',
    highlights: [
      'Visit all 7 hills',
      'Electric bikes (no sweat!)',
      'See 15+ landmarks',
      'Small group size'
    ],
    included: ['E-bike', 'Helmet', 'Guide', 'Water'],
    meetingPoint: 'Praça do Comércio',
    latitude: 38.7071,
    longitude: -9.1365,
    availableToday: false,
    instantBooking: true,
    verified: true,
  },
  {
    id: '8',
    title: 'Wine Tasting in Sintra',
    provider: 'Quinta da Regaleira',
    location: 'Sintra',
    distance: '28km away',
    price: 85,
    currency: '€',
    duration: '4h',
    rating: 5.0,
    reviewCount: 167,
    image: 'https://images.unsplash.com/photo-1506377247377-2a5b3b417ebb?w=800&q=80',
    category: 'Food & Drink',
    tags: ['Wine', 'Nature', 'Day Trip'],
    description: 'Escape to the magical hills of Sintra for an exclusive wine tasting at a historic quinta. Includes transport from Lisbon.',
    highlights: [
      'Taste 6 premium Portuguese wines',
      'Visit historic estate',
      'Gourmet cheese pairing',
      'Round-trip transport included'
    ],
    included: ['Transport', 'Wine tasting', 'Cheese board', 'Tour guide'],
    meetingPoint: 'Rossio Train Station (or hotel pickup)',
    latitude: 38.7969,
    longitude: -9.3897,
    availableToday: false,
    instantBooking: false,
    verified: true,
  },
];

export const CATEGORIES = [
  { id: 'all', name: 'All', icon: '🎯' },
  { id: 'workshop', name: 'Workshops', icon: '🎨' },
  { id: 'adventure', name: 'Adventure', icon: '⚡' },
  { id: 'food', name: 'Food & Drink', icon: '🍷' },
  { id: 'culture', name: 'Culture', icon: '🎭' },
  { id: 'nature', name: 'Nature', icon: '🌿' },
  { id: 'nightlife', name: 'Nightlife', icon: '🌙' },
];
